DROP TABLE IF EXISTS `test`;

CREATE TABLE `test` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `a`  TINYINT,
    `b`  SMALLINT,
    `c`  MEDIUMINT,
    `d`  INTEGER,
    `e`  BIGINT,
    `f`  DECIMAL(2, 1),
    `g`  NUMERIC(2, 1),
    `h`  FLOAT,
    `i`  DOUBLE,
    `j`  BIT(3),
    `k`  DATE,
    `l`  DATETIME,
    `m`  TIMESTAMP,
    `n`  TIME,
    `o`  YEAR,
    `p`  CHAR(4),
    `q`  VARCHAR(4),
    `r`  BINARY(4),
    `s`  VARBINARY(4),
    `t`  TINYBLOB,
    `u`  BLOB,
    `v`  MEDIUMBLOB,
    `w`  LONGBLOB,
    `x`  TINYTEXT,
    `y`  TEXT,
    `z`  MEDIUMTEXT,
    `aa` LONGTEXT,
    `ab` ENUM('foo', 'bar'),
    `ac` SET('foo', 'bar'),
    `ad` JSON,
    `ae` GEOMETRY,
    `af` POINT,
    `ag` LINESTRING,
    `ah` POLYGON,
    `ai` TINYINT UNSIGNED,
    `aj` MEDIUMINT UNSIGNED,
    `ak` INTEGER UNSIGNED,
    `al` BIGINT UNSIGNED,

    `xa` CHAR(4) COLLATE utf8mb4_bin,
    `xb` CHAR(4) BINARY,
    `xc` CHAR(4) CHARSET binary,
    `xd` TEXT COLLATE utf8mb4_bin,
    PRIMARY KEY(`id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `test` VALUES (
    NULL,
    1,
    1,
    1,
    1,
    1,
    1.1,
    1.1,
    1.1,
    1.1,
    0b111,
    '1000-01-01',
    '1000-01-01 01:01:01',
    '1970-01-01 00:01:01',
    '01:01:01',
    2006,
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    'aa',
    'foo',
    'foo,bar',
    '{"ad":null}',
    ST_GeomFromText('LINESTRING(0 0, 1 1, 2 0)'),
    POINT(1, 1),
    ST_GeomFromText('LINESTRING(0 0, 1 1, 2 0)'),
    ST_GeomFromText('Polygon((0 0,0 3,3 0,0 0),(1 1,1 2,2 1,1 1))'),
    1,
    1,
    1,
    1,
    'xa',
    'xb',
    'xc',
    'xd'
);
